// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mszyurpnapyxqbvwecmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zenl1cnBuYXB5eHFidndlY21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzA5NDcsImV4cCI6MjA2MjMwNjk0N30.ocwluouCZLgmordUWlOsZUaeB7Ff__8oLHM4vTyqKxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);